name: CI
on:
  push:
    branches: ["main"]

  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v4.1.1
      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Criação da Imagem docker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            rafaelsdomingos/ittalentdb:v${{ github.run_number }}
            rafaelsdomingos/ittalentdb:latest
